balanced: true
categories: get_organ_disease
cell_type: neuronal
data_root: /storage1/fs1/fuhai.li/Active/tianqi.x/OmniCellTOSG/dataset_outputs
dataset_output_dir: ./Output/data_ad_disease
device: 0
disease_name: Alzheimer's Disease
downstream_task: disease
gender: female
label_column: disease
num_omic_feature: 1
p: 1.0e-05
pre_alpha: 0.0
pre_cross_fusion_output_dim: 1
pre_decoder_dim: 4
pre_decoder_dropout: 0.2
pre_decoder_layers: 2
pre_graph_bn: false
pre_graph_encoder_activation: leaky_relu
pre_graph_encoder_dropout: 0.8
pre_graph_encoder_layers: 2
pre_graph_input_dim: 8
pre_graph_layer_type: gcn
pre_graph_output_dim: 8
pre_internal_bn: false
pre_internal_encoder_activation: leaky_relu
pre_internal_encoder_dropout: 0.8
pre_internal_encoder_layers: 1
pre_internal_input_dim: 1
pre_internal_layer_type: gcn
pre_internal_output_dim: 1
pre_lm_emb_dim: 1
pre_lr: 0.01
pre_weight_decay: 5.0e-05
pretrain_batch_size: 4
pretrain_num_workers: 0
pretrain_text_batch_size: 256
pretrained_model_save_path: ./Checkpoints/pretrained_models/pretrained_celltosg_foundation.pt
prot_model_name: nferruz/ProtGPT2
random_state: 2025
rna_model_name: dna_gpt0.1b_h
rna_seq_lm_model_path: ./Checkpoints/pretrained_dnagpt
rna_seq_max_len: 256
sample_ratio: 0.01
sample_size: null
shuffle: true
suspension_type: nucleus
text_lm_model_path: microsoft/deberta-v3-small
tissue: Cerebral Cortex
tissue_general: brain
train_bio: false
train_text: false
